# Generated by Django 5.0.2 on 2024-02-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='title',
            new_name='Listing',
        ),
    ]
