# Generated by Django 5.0.2 on 2024-02-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_title_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
