# Generated by Django 5.0.2 on 2024-02-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_name_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default='HH', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='official_homepage',
            field=models.CharField(default=2005, max_length=100),
            preserve_default=False,
        ),
    ]
