# Generated by Django 5.0.2 on 2024-02-15 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2005, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year_created',
            field=models.IntegerField(default=2005, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
