# Generated by Django 5.0.2 on 2024-02-15 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_year_formed_listing_year_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
