# Generated by Django 5.0.2 on 2024-02-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
